{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "991292ee",
   "metadata": {},
   "source": [
    "## Rahul Sai Samineni\n",
    "## IR - CS 582 - Final Project"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "7fee5838",
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "import os\n",
    "import re\n",
    "import pickle\n",
    "from bs4 import BeautifulSoup\n",
    "from collections import deque"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "699d6c7b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Could not connect to  https://give.engineering.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='give.engineering.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://emergency.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='emergency.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://give.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='give.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://gat.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='gat.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://tag.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='tag.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://fimmanager.vcas.uic.edu/maps/feedback\n",
      "Error occured:  HTTPSConnectionPool(host='fimmanager.vcas.uic.edu', port=443): Max retries exceeded with url: /maps/feedback (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://outlook.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='outlook.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://events.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='events.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://clery.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='clery.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://emergency.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='emergency.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://news.uic.edu/social-media-directory\n",
      "Error occured:  HTTPSConnectionPool(host='news.uic.edu', port=443): Max retries exceeded with url: /social-media-directory (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://accessweb.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='accessweb.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/rahulsaisamineni/opt/anaconda3/lib/python3.9/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features=\"xml\"` into the BeautifulSoup constructor.\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Could not connect to  http://careers.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='careers.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://gotime.uic.edu/login\n",
      "Error occured:  HTTPSConnectionPool(host='gotime.uic.edu', port=443): Max retries exceeded with url: /login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://www.housing.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='www.housing.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://www.ois.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='www.ois.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://globalhealth.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='globalhealth.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://commuter.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='commuter.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://help.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='help.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://emergency.uic.edu/uic-alerts\n",
      "Error occured:  HTTPSConnectionPool(host='emergency.uic.edu', port=443): Max retries exceeded with url: /uic-alerts (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://help.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='help.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://connect.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='connect.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://docs.financialaid.uic.edu/index.html\n",
      "Error occured:  HTTPSConnectionPool(host='docs.financialaid.uic.edu', port=443): Max retries exceeded with url: /index.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://healthcheck.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='healthcheck.uic.edu', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9bf17eba90>: Failed to establish a new connection: [Errno 60] Operation timed out'))  \n",
      "\n",
      "Could not connect to  http://teams.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='teams.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://go.uic.edu/dailypass\n",
      "Error occured:  HTTPSConnectionPool(host='healthcheck.uic.edu', port=443): Max retries exceeded with url: /AAMEmployeeOnsiteStatus/Home/CheckStatus (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9bf17bc940>: Failed to establish a new connection: [Errno 60] Operation timed out'))  \n",
      "\n",
      "Could not connect to  http://go.uic.edu/dailysurvey\n",
      "Error occured:  HTTPSConnectionPool(host='healthcheck.uic.edu', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9bf19512b0>: Failed to establish a new connection: [Errno 60] Operation timed out'))  \n",
      "\n",
      "Could not connect to  https://sae.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='sae.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://theory.cs.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='theory.cs.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://aes.uic.edu/aes-staff\n",
      "Error occured:  HTTPSConnectionPool(host='aes.uic.edu', port=443): Max retries exceeded with url: /aes-staff (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://password.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='password.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://bound.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='bound.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://majors.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='majors.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://news.uic.edu/uicnews\n",
      "Error occured:  HTTPSConnectionPool(host='news.uic.edu', port=443): Max retries exceeded with url: /uicnews (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://webmail.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='webmail.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://http://ahs.uic.edu\n",
      "Error occured:  HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //ahs.uic.edu (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bf14bfca0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))  \n",
      "\n",
      "Could not connect to  http://www.psych.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='www.psych.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://www.psych.uic.edu/research/center-on-mental-health-services-research-and-policy/about-us/about-the-center\n",
      "Error occured:  HTTPSConnectionPool(host='www.psych.uic.edu', port=443): Max retries exceeded with url: /research/center-on-mental-health-services-research-and-policy/about-us/about-the-center (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://www.psych.uic.edu/research/center-on-mental-health-services-research-and-policy/our-team\n",
      "Error occured:  HTTPSConnectionPool(host='www.psych.uic.edu', port=443): Max retries exceeded with url: /research/center-on-mental-health-services-research-and-policy/our-team (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Could not connect to  https://archive.news.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='archive.news.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://logos.uic.edu/index.cgi\n",
      "Error occured:  HTTPSConnectionPool(host='logos.uic.edu', port=443): Max retries exceeded with url: /index.cgi (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://www.hr.uic.edu/policies\n",
      "Error occured:  HTTPSConnectionPool(host='www.hr.uic.edu', port=443): Max retries exceeded with url: /policies (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://www.campuscare.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='www.campuscare.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://www.campuscare.uic.edu/covid-19-information\n",
      "Error occured:  HTTPSConnectionPool(host='www.campuscare.uic.edu', port=443): Max retries exceeded with url: /covid-19-information (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://accountportal.uic.edu/auth/manage\n",
      "Error occured:  HTTPSConnectionPool(host='accountportal.uic.edu', port=443): Max retries exceeded with url: /auth/manage (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://news.uic.edu/uic-ranks-high-on-list-of-worlds-young-universities\n",
      "Error occured:  HTTPSConnectionPool(host='news.uic.edu', port=443): Max retries exceeded with url: /uic-ranks-high-on-list-of-worlds-young-universities (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://www.ois.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='www.ois.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://gotime.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='gotime.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://apps.pharmacy.uic.edu/depts/aaa/profile_photos\n",
      "Error occured:  HTTPSConnectionPool(host='apps.pharmacy.uic.edu', port=443): Max retries exceeded with url: /depts/aaa/profile_photos (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://campusprograms.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='campusprograms.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://campusprograms.uic.edu/solist.shtml\n",
      "Error occured:  HTTPSConnectionPool(host='campusprograms.uic.edu', port=443): Max retries exceeded with url: /solist.shtml (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://uicforum.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='uicforum.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://saonline.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='saonline.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://tigger.uic.edu/depts/oar/undergrad/transfer_requirements_undergrad.html\n",
      "Error occured:  HTTPSConnectionPool(host='tigger.uic.edu', port=443): Max retries exceeded with url: /depts/oar/undergrad/transfer_requirements_undergrad.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9bf14d9fa0>: Failed to establish a new connection: [Errno 60] Operation timed out'))  \n",
      "\n",
      "Could not connect to  http://www.uic.edu/uic/studentlife/campus/emergency-information.shtml\n",
      "Error occured:  HTTPSConnectionPool(host='emergency.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://web-travel-prod.cc.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='web-travel-prod.cc.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://www.nursing.uic.edu/about-us/global-health\n",
      "Error occured:  HTTPSConnectionPool(host='www.nursing.uic.edu', port=443): Max retries exceeded with url: /about-us/global-health (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://www.nursing.uic.edu/about-us/global-health\n",
      "Error occured:  HTTPSConnectionPool(host='www.nursing.uic.edu', port=443): Max retries exceeded with url: /about-us/global-health (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://listserv.uic.edu/cgi-bin/wa\n",
      "Error occured:  HTTPSConnectionPool(host='listserv.uic.edu', port=443): Max retries exceeded with url: /cgi-bin/wa (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://hsi.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='hsi.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://vpua.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='vpua.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://hsi.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='hsi.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://aes.uic.edu/programs/presidents-award-program.html\n",
      "Error occured:  HTTPSConnectionPool(host='aes.uic.edu', port=443): Max retries exceeded with url: /programs/presidents-award-program.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Could not connect to  https://ure.uic.edu/facfws.php\n",
      "Error occured:  HTTPSConnectionPool(host='ure.uic.edu', port=443): Max retries exceeded with url: /facfws.php (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://jmls.uic.edu/student-support/diversity\n",
      "Error occured:  HTTPSConnectionPool(host='jmls.uic.edu', port=443): Max retries exceeded with url: /student-support/diversity (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://jmls.uic.edu/student-support/diversity/transparency-project\n",
      "Error occured:  HTTPSConnectionPool(host='jmls.uic.edu', port=443): Max retries exceeded with url: /student-support/diversity/transparency-project (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://jmls.uic.edu/student-support/students/counseling\n",
      "Error occured:  HTTPSConnectionPool(host='jmls.uic.edu', port=443): Max retries exceeded with url: /student-support/students/counseling (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://jmls.uic.edu/student-support/organizations\n",
      "Error occured:  HTTPSConnectionPool(host='jmls.uic.edu', port=443): Max retries exceeded with url: /student-support/organizations (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://dragoncenter.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='dragoncenter.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://studentaffairs.uic.edu/upass_pickup/index2.php\n",
      "Error occured:  HTTPSConnectionPool(host='studentaffairs.uic.edu', port=443): Max retries exceeded with url: /upass_pickup/index2.php (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://jmls.uic.edu/security/ctaupass\n",
      "Error occured:  HTTPSConnectionPool(host='jmls.uic.edu', port=443): Max retries exceeded with url: /security/ctaupass (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://vcsa.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='vcsa.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://convocation.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='convocation.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://wow.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='wow.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://studentaffairs.uic.edu/wordpresspreview/scw/scw.html\n",
      "Error occured:  HTTPSConnectionPool(host='studentaffairs.uic.edu', port=443): Max retries exceeded with url: /wordpresspreview/scw/scw.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://studentaffairs.uic.edu/wordpresspreview/sce/sce.html\n",
      "Error occured:  HTTPSConnectionPool(host='studentaffairs.uic.edu', port=443): Max retries exceeded with url: /wordpresspreview/sce/sce.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://service.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='service.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://vcsa.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='vcsa.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://go.uic.edu/findservice\n",
      "Error occured:  HTTPSConnectionPool(host='service.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://clce.uic.edu/about/donate\n",
      "Error occured:  HTTPSConnectionPool(host='clce.uic.edu', port=443): Max retries exceeded with url: /about/donate (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://vote.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='vote.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://office.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='office.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://events.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='events.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://desktop.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='desktop.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://www.hr.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='www.hr.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://web-travel-prod.cc.uic.edu/index.html\n",
      "Error occured:  HTTPSConnectionPool(host='web-travel-prod.cc.uic.edu', port=443): Max retries exceeded with url: /index.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://accountportal.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='accountportal.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://parkingservices.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='parkingservices.uic.edu', port=443): Max retries exceeded with url: /Home (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Could not connect to  https://jmls.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='jmls.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://vpape.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='vpape.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://logos.uic.edu/index.cgi\n",
      "Error occured:  HTTPSConnectionPool(host='logos.uic.edu', port=443): Max retries exceeded with url: /index.cgi (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://web.bme.uic.edu/bme-wp/bme-undergrad/curr_flow_fa21present.htm\n",
      "Error occured:  HTTPSConnectionPool(host='web.bme.uic.edu', port=443): Max retries exceeded with url: /bme-wp/bme-undergrad/curr_flow_fa21present.htm (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://web.bme.uic.edu/bme-wp/bme-undergrad/curr_flow_fa16sp21.htm\n",
      "Error occured:  HTTPSConnectionPool(host='web.bme.uic.edu', port=443): Max retries exceeded with url: /bme-wp/bme-undergrad/curr_flow_fa16sp21.htm (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://merrp.engr.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='merrp.engr.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://vcsa.uic.edu/scholarships/dr-martin-scholarship\n",
      "Error occured:  HTTPSConnectionPool(host='vcsa.uic.edu', port=443): Max retries exceeded with url: /scholarships/dr-martin-scholarship (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://www.psych.uic.edu/education/continuing-education\n",
      "Error occured:  HTTPSConnectionPool(host='www.psych.uic.edu', port=443): Max retries exceeded with url: /education/continuing-education (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://eyecare.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='eyecare.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://www.nursing.uic.edu/campus/quad-cities\n",
      "Error occured:  HTTPSConnectionPool(host='www.nursing.uic.edu', port=443): Max retries exceeded with url: /campus/quad-cities (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://www.nursing.uic.edu/campus/springfield\n",
      "Error occured:  HTTPSConnectionPool(host='www.nursing.uic.edu', port=443): Max retries exceeded with url: /campus/springfield (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://www.nursing.uic.edu/campus/urbana\n",
      "Error occured:  HTTPSConnectionPool(host='www.nursing.uic.edu', port=443): Max retries exceeded with url: /campus/urbana (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://mmnl.engr.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='mmnl.engr.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://bioe.uic.edu/bioe-events/research-symposium\n",
      "Error occured:  HTTPSConnectionPool(host='bioe.uic.edu', port=443): Max retries exceeded with url: /bioe-events/research-symposium (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://csun.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='csun.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://bioe.uic.edu/news-stories/best-bioengineering-experience-for-science-teachers-at-uic\n",
      "Error occured:  HTTPSConnectionPool(host='bioe.uic.edu', port=443): Max retries exceeded with url: /news-stories/best-bioengineering-experience-for-science-teachers-at-uic (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://bioe.uic.edu/news-stories/kotche-named-notable-woman-in-stem-by-crains-chicago-business\n",
      "Error occured:  HTTPSConnectionPool(host='bioe.uic.edu', port=443): Max retries exceeded with url: /news-stories/kotche-named-notable-woman-in-stem-by-crains-chicago-business (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://nrl.ece.uic.edu/people.html\n",
      "Error occured:  HTTPSConnectionPool(host='nrl.ece.uic.edu', port=443): Max retries exceeded with url: /people.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://isnl.lab.uic.edu/isnl-dr.-tolou-shokuhfar.html\n",
      "Error occured:  HTTPSConnectionPool(host='isnl.lab.uic.edu', port=443): Max retries exceeded with url: /isnl-dr.-tolou-shokuhfar.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://bestbioe.lab.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='bestbioe.lab.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://bioe.uic.edu/news-stories/coe-makerspace-steps-up-to-shield-healthcare-providers-during-pandemic\n",
      "Error occured:  HTTPSConnectionPool(host='bioe.uic.edu', port=443): Max retries exceeded with url: /news-stories/coe-makerspace-steps-up-to-shield-healthcare-providers-during-pandemic (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://aiaa.engr.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='aiaa.engr.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://lazarov.lab.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='lazarov.lab.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Could not connect to  https://saggere.lab.uic.edu/index.html\n",
      "Error occured:  HTTPSConnectionPool(host='saggere.lab.uic.edu', port=443): Max retries exceeded with url: /index.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://wiep.engr.uic.edu/wiesp\n",
      "Error occured:  HTTPSConnectionPool(host='wiep.engr.uic.edu', port=443): Max retries exceeded with url: /wiesp (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://acoustics.mie.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='acoustics.mie.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://translog.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='translog.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://www.ece.uic.edu\n",
      "Error occured:  HTTPConnectionPool(host='www.ece.uic.edu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bf180cc40>: Failed to establish a new connection: [Errno 61] Connection refused'))  \n",
      "\n",
      "Could not connect to  https://csun.uic.edu/index.html\n",
      "Error occured:  HTTPSConnectionPool(host='csun.uic.edu', port=443): Max retries exceeded with url: /index.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://www.csun.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='www.csun.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://shi.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='shi.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://nanoeng.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='nanoeng.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://geotech.lab.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='geotech.lab.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://wiep.engr.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='wiep.engr.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://www.mie.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='www.mie.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://news.uic.edu/app-that-tracks-bipolar-manic-depressive-episodes-wins-award\n",
      "Error occured:  HTTPSConnectionPool(host='news.uic.edu', port=443): Max retries exceeded with url: /app-that-tracks-bipolar-manic-depressive-episodes-wins-award (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://rc.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='rc.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://news.uic.edu/saber-builds-campus-computing-backbone\n",
      "Error occured:  HTTPSConnectionPool(host='news.uic.edu', port=443): Max retries exceeded with url: /saber-builds-campus-computing-backbone (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://news.uic.edu/uic-bioengineer-receives-fulbright-to-study-in-finland\n",
      "Error occured:  HTTPSConnectionPool(host='news.uic.edu', port=443): Max retries exceeded with url: /uic-bioengineer-receives-fulbright-to-study-in-finland (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://strc.evl.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='strc.evl.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://news.uic.edu/bioengineering-student-awarded-gates-cambridge-scholarship\n",
      "Error occured:  HTTPSConnectionPool(host='news.uic.edu', port=443): Max retries exceeded with url: /bioengineering-student-awarded-gates-cambridge-scholarship (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://news.uic.edu/bubble-recoil-could-be-used-to-cool-microchips-even-in-space\n",
      "Error occured:  HTTPSConnectionPool(host='news.uic.edu', port=443): Max retries exceeded with url: /bubble-recoil-could-be-used-to-cool-microchips-even-in-space (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://www.erc.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='www.erc.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://sae.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='sae.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://news.uic.edu/5m-federal-grant-to-help-uic-graduate-more-latino-scientists-engineers\n",
      "Error occured:  HTTPSConnectionPool(host='news.uic.edu', port=443): Max retries exceeded with url: /5m-federal-grant-to-help-uic-graduate-more-latino-scientists-engineers (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://news.uic.edu/can-cellphone-use-predict-manic-episodes-in-bipolar-disorder\n",
      "Error occured:  HTTPSConnectionPool(host='news.uic.edu', port=443): Max retries exceeded with url: /can-cellphone-use-predict-manic-episodes-in-bipolar-disorder (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://news.uic.edu/new-nanomaterial-offers-promise-in-bendable-wearable-electronic-devices\n",
      "Error occured:  HTTPSConnectionPool(host='news.uic.edu', port=443): Max retries exceeded with url: /new-nanomaterial-offers-promise-in-bendable-wearable-electronic-devices (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Could not connect to  http://www.erc.uic.edu/biofuels-bioenergy/pollinator-habitat/rights-of-way-as-habitat\n",
      "Error occured:  HTTPSConnectionPool(host='www.erc.uic.edu', port=443): Max retries exceeded with url: /biofuels-bioenergy/pollinator-habitat/rights-of-way-as-habitat (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://kenbrez.lab.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='kenbrez.lab.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://nanomaterialsenergysystems.engr.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='nanomaterialsenergysystems.engr.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://news.uic.edu/graphene-sandwich-improves-imaging-of-biomolecules\n",
      "Error occured:  HTTPSConnectionPool(host='news.uic.edu', port=443): Max retries exceeded with url: /graphene-sandwich-improves-imaging-of-biomolecules (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://news.uic.edu/graphene-nano-sensor-depends-on-defects-for-sensitivity\n",
      "Error occured:  HTTPSConnectionPool(host='news.uic.edu', port=443): Max retries exceeded with url: /graphene-nano-sensor-depends-on-defects-for-sensitivity (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://news.uic.edu/graphene-heat-transfer-riddle-unravelled\n",
      "Error occured:  HTTPSConnectionPool(host='news.uic.edu', port=443): Max retries exceeded with url: /graphene-heat-transfer-riddle-unravelled (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://news.uic.edu/supersonic-spray-delivers-high-quality-graphene-layer\n",
      "Error occured:  HTTPSConnectionPool(host='news.uic.edu', port=443): Max retries exceeded with url: /supersonic-spray-delivers-high-quality-graphene-layer (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://healthcheck.uic.edu\n",
      "Error occured:  HTTPConnectionPool(host='healthcheck.uic.edu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bf14e8850>: Failed to establish a new connection: [Errno 60] Operation timed out'))  \n",
      "\n",
      "Could not connect to  https://go.uic.edu/dailypass\n",
      "Error occured:  HTTPSConnectionPool(host='healthcheck.uic.edu', port=443): Max retries exceeded with url: /AAMEmployeeOnsiteStatus/Home/CheckStatus (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9bf14f25e0>: Failed to establish a new connection: [Errno 60] Operation timed out'))  \n",
      "\n",
      "Could not connect to  https://bioe.uic.edu/faculty-and-staff/faculty\n",
      "Error occured:  HTTPSConnectionPool(host='bioe.uic.edu', port=443): Max retries exceeded with url: /faculty-and-staff/faculty (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://alumni.jmls.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='alumni.jmls.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://ripl.jmls.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='ripl.jmls.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://jmls.uic.edu/student-support/diversity/access\n",
      "Error occured:  HTTPSConnectionPool(host='jmls.uic.edu', port=443): Max retries exceeded with url: /student-support/diversity/access (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://jmls.uic.edu/summer-prelaw-program\n",
      "Error occured:  HTTPSConnectionPool(host='jmls.uic.edu', port=443): Max retries exceeded with url: /summer-prelaw-program (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://jmls.uic.edu/student-support/diversity/success\n",
      "Error occured:  HTTPSConnectionPool(host='jmls.uic.edu', port=443): Max retries exceeded with url: /student-support/diversity/success (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://jmls.uic.edu/student-support/diversity/cultural-centers\n",
      "Error occured:  HTTPSConnectionPool(host='jmls.uic.edu', port=443): Max retries exceeded with url: /student-support/diversity/cultural-centers (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://jmls.uic.edu/student-support/students/wellness-resources\n",
      "Error occured:  HTTPSConnectionPool(host='jmls.uic.edu', port=443): Max retries exceeded with url: /student-support/students/wellness-resources (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://hci.cs.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='hci.cs.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://activatenetid.accc.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='activatenetid.accc.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://commuter.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='commuter.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://bioe.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='bioe.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://ure.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='ure.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://www.nursing.uic.edu/about-us/midwest-nursing-history-research-center\n",
      "Error occured:  HTTPSConnectionPool(host='www.nursing.uic.edu', port=443): Max retries exceeded with url: /about-us/midwest-nursing-history-research-center (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Could not connect to  https://clery.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='clery.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://ossp.uic.edu/scholarships\n",
      "Error occured:  HTTPSConnectionPool(host='ossp.uic.edu', port=443): Max retries exceeded with url: /scholarships (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://hjpwd.ahslabs.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='hjpwd.ahslabs.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://www.ois.uic.edu/students/prospective/declaration_and_certification_of_finances___d_c_f_\n",
      "Error occured:  HTTPSConnectionPool(host='www.ois.uic.edu', port=443): Max retries exceeded with url: /students/prospective/declaration_and_certification_of_finances___d_c_f_ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://ccspd.org.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='ccspd.org.uic.edu', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9bf1514940>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))  \n",
      "\n",
      "Could not connect to  https://www.psych.uic.edu/research/center-on-mental-health-services-research-and-policy/about-us/about-the-centerpublications.htm\n",
      "Error occured:  HTTPSConnectionPool(host='www.psych.uic.edu', port=443): Max retries exceeded with url: /research/center-on-mental-health-services-research-and-policy/about-us/about-the-centerpublications.htm (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://flamestutoring.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='flamestutoring.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://www.psych.uic.edu/clinical/adult-services\n",
      "Error occured:  HTTPSConnectionPool(host='www.psych.uic.edu', port=443): Max retries exceeded with url: /clinical/adult-services (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://fmweb.fm.uic.edu\n",
      "Error occured:  HTTPConnectionPool(host='fmweb.fm.uic.edu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bf15842e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))  \n",
      "\n",
      "Could not connect to  http://www.uic.edu/cuppa/upp\n",
      "Error occured:  HTTPSConnectionPool(host='upp.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://commuter.uic.edu/housing\n",
      "Error occured:  HTTPSConnectionPool(host='commuter.uic.edu', port=443): Max retries exceeded with url: /housing (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://www.psych.uic.edu/profile/brittany-n-rudd\n",
      "Error occured:  HTTPSConnectionPool(host='www.psych.uic.edu', port=443): Max retries exceeded with url: /profile/brittany-n-rudd (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://https://comm.uic.edu/prowp-content/uploads/zizi-papacharissi\n",
      "Error occured:  HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //comm.uic.edu/prowp-content/uploads/zizi-papacharissi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bf0caf160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))  \n",
      "\n",
      "Could not connect to  http://www.psych.uic.edu/154-about-us/directory/faculty/266-steve-weine\n",
      "Error occured:  HTTPSConnectionPool(host='www.psych.uic.edu', port=443): Max retries exceeded with url: /154-about-us/directory/faculty/266-steve-weine (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://www.ois.uic.edu/resources/insurance\n",
      "Error occured:  HTTPSConnectionPool(host='www.ois.uic.edu', port=443): Max retries exceeded with url: /resources/insurance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://www.hr.uic.edu/hiring/hiringuiretiree\n",
      "Error occured:  HTTPSConnectionPool(host='www.hr.uic.edu', port=443): Max retries exceeded with url: /hiring/hiringuiretiree (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://www.uic.edu/depts/hr/html/exitchecklistfinal.htm\n",
      "Error occured:  HTTPSConnectionPool(host='www.hr.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://www.hr.uic.edu/classification_and_compensation/about_civil_service\n",
      "Error occured:  HTTPSConnectionPool(host='www.hr.uic.edu', port=443): Max retries exceeded with url: /classification_and_compensation/about_civil_service (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://uep.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='uep.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://gonext.uic.edu\n",
      "Error occured:  HTTPConnectionPool(host='gonext.uic.edu', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bf1694970>: Failed to establish a new connection: [Errno 60] Operation timed out'))  \n",
      "\n",
      "Could not connect to  http://uicarchives.library.uic.edu/exhibits\n",
      "Error occured:  HTTPSConnectionPool(host='uicarchives.library.uic.edu', port=443): Max retries exceeded with url: /exhibits (Caused by SSLError(CertificateError(\"hostname 'uicarchives.library.uic.edu' doesn't match either of 'scalar-prod.lib.uic.edu', 'exhibits.library.uic.edu', 'rjd.library.uic.edu', 'www.exhibits.library.uic.edu', 'www.rjd.library.uic.edu', 'www.scalar-prod.lib.uic.edu'\")))  \n",
      "\n",
      "Could not connect to  https://groups.accc.uic.edu\n",
      "Error occured:  HTTPSConnectionPool(host='groups.accc.uic.edu', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  http://www.jmls.uic.edu/library/index.asp\n",
      "Error occured:  HTTPConnectionPool(host='www.jmls.uic.edu', port=80): Max retries exceeded with url: /library/index.asp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bf1fc3910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))  \n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Could not connect to  https://jmls.uic.edu/coronavirus\n",
      "Error occured:  HTTPSConnectionPool(host='jmls.uic.edu', port=443): Max retries exceeded with url: /coronavirus (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://www.ois.uic.edu/faculty__staff__and_scholars/j/categories\n",
      "Error occured:  HTTPSConnectionPool(host='www.ois.uic.edu', port=443): Max retries exceeded with url: /faculty__staff__and_scholars/j/categories (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://www.hr.uic.edu/managing_my_performance/annual_performance_review\n",
      "Error occured:  HTTPSConnectionPool(host='www.hr.uic.edu', port=443): Max retries exceeded with url: /managing_my_performance/annual_performance_review (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://jmls.uic.edu/security/discrimination-form\n",
      "Error occured:  HTTPSConnectionPool(host='jmls.uic.edu', port=443): Max retries exceeded with url: /security/discrimination-form (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))  \n",
      "\n",
      "Could not connect to  https://jmls.uic.edu/security/title-ix-form\n",
      "Error occured:  HTTPSConnectionPool(host='jmls.uic.edu', port=443): Max retries exceeded with url: /security/title-ix-form (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))  \n",
      "\n"
     ]
    }
   ],
   "source": [
    "domain = \"uic.edu\"\n",
    "start_url = \"https://cs.uic.edu\"                \n",
    "\n",
    "pages_folder = \"../PagesFetched/\"\n",
    "\n",
    "# file extensions to ignore while crawling pages\n",
    "ignore_extensions = [\n",
    "    '.pdf', '.doc', '.docx', '.ppt', '.pptx', '.xls', '.xlsx', '.css', '.js',\n",
    "    '.aspx', '.png', '.jpg', '.jpeg', '.gif', '.svg', '.ico', '.mp4',\n",
    "    '.avi', '.tar', '.gz', '.tgz', '.zip'\n",
    "]\n",
    "\n",
    "crawl_limit = 6000\n",
    "\n",
    "# to make sure error log file is initially empty\n",
    "error_file = \"../error_log.txt\"\n",
    "f = open(error_file, \"w+\")\n",
    "# f.truncate()\n",
    "f.close()\n",
    "\n",
    "# queue to perform BFS web traversal\n",
    "url_queue = deque()\n",
    "url_queue.append(start_url)\n",
    "\n",
    "# list to keep track of traversed URLs\n",
    "urls_crawled = []\n",
    "urls_crawled.append(start_url)\n",
    "\n",
    "# dict to track pages fetched and stored in folder\n",
    "pages_crawled = {}\n",
    "page_no = 0\n",
    "\n",
    "while url_queue:\n",
    "    \n",
    "    try:\n",
    "        url = url_queue.popleft()               # fetch the first URL from the queue\n",
    "        request = requests.get(url)            # get html code of web page\n",
    "\n",
    "        if (request.status_code == 200):\n",
    "            \n",
    "            soup = BeautifulSoup(request.text, 'lxml')\n",
    "            tags_extracted = soup.find_all('a')                 # extract all 'a' tags from page\n",
    "            \n",
    "            if len(tags_extracted) != 0:                        # to reject pages which don't link to another page\n",
    "                pages_crawled[page_no] = url    \n",
    "\n",
    "                output_file = pages_folder + str(page_no)\n",
    "\n",
    "                os.makedirs(os.path.dirname(output_file), exist_ok=True)     # create file to store html code\n",
    "\n",
    "                with open(output_file, \"w\", encoding=\"utf-8\") as file:\n",
    "                    file.write(request.text)\n",
    "                file.close()\n",
    "\n",
    "                for tag in tags_extracted:\n",
    "\n",
    "                    link = tag.get('href')                  \n",
    "\n",
    "                    if link is not None and link.startswith(\"http\") and not any(ext in link.lower() for ext in ignore_extensions):\n",
    "                        \n",
    "                        link = link.lower()\n",
    "                        link = link.split('#')[0]\n",
    "                        link = link.split('?', maxsplit=1)[0]\n",
    "                        link = link.rstrip('/')\n",
    "                        link = link.strip()\n",
    "\n",
    "                        if link not in urls_crawled and domain in link:\n",
    "                            url_queue.append(link)                 # valid URL to append to the queue\n",
    "                            urls_crawled.append(link)\n",
    "\n",
    "                if (len(pages_crawled) > crawl_limit):\n",
    "                    break                                       # stop crawling when reached limit\n",
    "\n",
    "                page_no += 1\n",
    "            \n",
    "\n",
    "    except Exception as e:\n",
    "        with open(error_file, \"a+\") as log:                  # add error message to error log\n",
    "            log.write(f\"Could not connect to {url}\")\n",
    "            log.write(f\"\\nError occured: {e}\\n\\n\")\n",
    "        file.close()\n",
    "\n",
    "        print(\"Could not connect to \", url)\n",
    "        print(\"Error occured: \", e, \" \\n\")\n",
    "        continue\n",
    "        \n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "83e2f1b3",
   "metadata": {},
   "outputs": [],
   "source": [
    "pickle_folder = \"../Pickle/\"\n",
    "os.makedirs(pickle_folder, exist_ok=True)\n",
    "\n",
    "# Pickling the dict of crawled pages\n",
    "with open(pickle_folder + '6k_pages_crawled.pickle', 'wb') as f:\n",
    "    pickle.dump(pages_crawled,f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "8387e727",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "6001"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "len(pages_crawled)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "dca3277e",
   "metadata": {},
   "outputs": [],
   "source": [
    "pickle_folder = \"../Pickle/\"\n",
    "os.makedirs(pickle_folder, exist_ok=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "f986504d",
   "metadata": {},
   "outputs": [],
   "source": [
    "with open(pickle_folder + '6k_pages_crawled.pickle', 'rb') as f:\n",
    "    pages = pickle.load(f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "6074fd8b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pages_crawled == pages"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f0f6d65e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10.7 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.7"
  },
  "vscode": {
   "interpreter": {
    "hash": "aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
